/**
 * The design, checked against the built HTML.
 *
 * Every value in the design was measured rather than estimated, so these are
 * equality checks rather than sanity checks: a token that drifts is a
 * regression, not a matter of taste. They run over `build/client`, which is
 * what a reader actually receives.
 */

import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { describe, test } from 'node:test'
import { DOT_COLOURS, TOKENS } from '../app/lib/palette.ts'
import { THEME_KEY } from '../app/lib/theme.ts'

const BUILD = path.resolve(import.meta.dirname, '../build/client')
const STYLES = path.resolve(import.meta.dirname, '../app/styles')

async function stylesheet(name: string): Promise<string> {
  return readFile(path.join(STYLES, name), 'utf8')
}

async function page(route: string): Promise<string> {
  return readFile(path.join(BUILD, route, 'index.html'), 'utf8')
}

describe('the palette', () => {
  test('keeps oklch for everything that is not animated', async () => {
    const tokens = await stylesheet('tokens.css')

    // A hex value here means someone converted a colour and broke the family's
    // near-equal lightness. Only the animated ones are allowed to be hex.
    const hexes = [...tokens.matchAll(/#[0-9a-fA-F]{3,8}\b/g)].map((match) => match[0])
    const allowed = new Set([
      '#4e3c48', // --text-nav, animated to pink
      '#d1519a', // --text-nav-hover
      '#ea5da9', // logo dot 1
      '#ad8dfd', // logo dot 2
      '#e9c85e', // logo dot 3
      '#3fbe93', // the mint the dots tween to
      '#1f7a5b', // the check beside the wordmark
    ])

    const unexpected = hexes.filter((hex) => !allowed.has(hex.toLowerCase()))
    assert.deepEqual(unexpected, [])
  })

  test('the JavaScript copy of it says the same thing as the stylesheet', async () => {
    // GSAP interpolates hex, so the tweened colours have to exist in
    // JavaScript as well as in CSS. That second spelling is unavoidable; a
    // third is not, and there were two more -- the icon generator and the
    // social card each typed the dots out again. They now read
    // app/lib/palette.ts, and this is what stops palette.ts drifting from the
    // stylesheet that defines the brand.
    const tokens = await stylesheet('tokens.css')

    for (const [name, expected] of Object.entries(TOKENS)) {
      const declared = new RegExp(`${name}:\\s*(#[0-9a-fA-F]{3,8})`).exec(tokens)?.[1]
      assert.equal(
        declared?.toLowerCase(),
        expected.toLowerCase(),
        `${name} is ${declared} in tokens.css and ${expected} in app/lib/palette.ts`,
      )
    }
  })

  test('the favicon is drawn in the brand colours, not a copy of them', async () => {
    // public/icon.svg is generated by `pnpm run icons:make` and committed, so
    // nothing regenerates it on a build. This is what notices when the brand
    // moves and the icon does not.
    const icon = await readFile(path.resolve(import.meta.dirname, '../public/icon.svg'), 'utf8')
    const fills = [...icon.matchAll(/fill="(#[0-9a-fA-F]{3,8})"/g)].map((match) =>
      (match[1] ?? '').toLowerCase(),
    )
    assert.deepEqual(fills, [...DOT_COLOURS])
  })

  test('defines the five gradients and no more', async () => {
    const tokens = await stylesheet('tokens.css')
    for (const gradient of [
      '--gradient-cta:',
      '--gradient-cta-hover:',
      '--gradient-marker:',
      '--gradient-code:',
      '--gradient-hairline:',
    ]) {
      assert.ok(tokens.includes(gradient), `missing ${gradient}`)
    }
  })

  test('shadows are tinted pink, never grey', async () => {
    const tokens = await stylesheet('tokens.css')
    const shadows = [...tokens.matchAll(/--shadow-[a-z]+:([^;]+);/g)].map((match) => match[1] ?? '')
    assert.ok(shadows.length >= 4)
    for (const shadow of shadows) {
      // Either an oklch tint or the one documented rgb pill shadow.
      assert.ok(
        shadow.includes('oklch(') || shadow.includes('rgb(177 58 124'),
        `grey shadow: ${shadow.trim()}`,
      )
    }
  })

  test('the dark theme flips every documentation token', async () => {
    const tokens = await stylesheet('tokens.css')
    const light = tokens.slice(tokens.indexOf('--bg: oklch(0.985'))
    const dark = tokens.slice(tokens.indexOf('[data-theme="dark"]'))

    // Each of these must be redefined under the dark selector, or something on
    // the page keeps a light value and goes illegible.
    for (const token of ['--bg', '--panel', '--fg', '--border', '--pink', '--code-bg']) {
      assert.ok(light.includes(`${token}:`), `${token} missing from light`)
      assert.ok(dark.includes(`${token}:`), `${token} missing from dark`)
    }
  })
})

describe('the documentation surface', () => {
  test('never styles itself with a marketing token', async () => {
    // These do not flip with the theme. Using one inside the docs is how a
    // component ends up unreadable in dark mode.
    const docs = await stylesheet('docs.css')
    const content = await stylesheet('content.css')

    for (const sheet of [docs, content]) {
      for (const token of ['--text-strong', '--text-body', '--surface-sunken', '--surface-card']) {
        assert.ok(!sheet.includes(`var(${token})`), `documentation CSS uses ${token}`)
      }
    }
  })

  test('code wraps rather than scrolling', async () => {
    // `pre-wrap` alone leaves a long identifier as one unbreakable token.
    const content = await stylesheet('content.css')
    assert.ok(content.includes('overflow-wrap: anywhere'))
    assert.ok(content.includes('white-space: pre-wrap'))
  })

  test('the heading anchor is revealed in CSS, not by a JS handler', async () => {
    // Bound imperatively, the listeners are lost on the next render and the
    // controls ship permanently invisible.
    const content = await stylesheet('content.css')
    assert.ok(content.includes(':hover .heading-anchor'))
    assert.ok(content.includes(':focus-within .heading-anchor'))
  })
})

describe('the built pages', () => {
  test('self-host both webfonts', async () => {
    const html = await page('')
    assert.ok(!html.includes('fonts.googleapis.com'), 'the page still calls Google Fonts')
    assert.ok(!html.includes('fonts.gstatic.com'))
  })

  test('settle the theme before first paint', async () => {
    const html = await page('docs')
    // Without a blocking script in the head, a reader who chose dark gets a
    // white flash on every navigation, because every page is static HTML.
    //
    // Asserted against the constant, not a string typed here. The key used to
    // be spelled twice -- once in the toggle that writes it, once inside the
    // head script that reads it -- and this test spelled it a third time, so
    // renaming it in one place would have left the test passing while every
    // dark-mode reader flashed white on all 38 pages.
    assert.ok(html.includes(THEME_KEY), `no ${THEME_KEY} in the document`)
    assert.ok(
      html.indexOf(THEME_KEY) < html.indexOf('</head>'),
      'the theme script is not in the head',
    )
  })

  test('draw the theme icon from the stylesheet, not from React', async () => {
    const html = await page('docs')
    // Both glyphs ship and CSS picks one, because the head script knows the
    // theme before the first paint and React does not know it until hydration.
    // Measured on a throttled connection, a state-driven icon left a sun on a
    // fully dark page for the whole three-second sample.
    for (const icon of ['sun', 'moon']) {
      assert.ok(html.includes(`data-icon="${icon}"`), `the ${icon} icon is not in the static HTML`)
    }
    const docs = await stylesheet('docs.css')
    assert.ok(
      docs.includes('[data-theme="dark"] .docs-theme-icon[data-icon="sun"]'),
      'nothing hides the sun in dark mode',
    )
  })

  test('name the modifier key the reader actually has', async () => {
    const html = await page('docs')
    // `⌘K` was baked into all 38 pages. Both spellings ship now, and the same
    // head script stamps `data-platform` for the stylesheet to choose between.
    assert.ok(html.includes('data-key="ctrl"'), 'no Ctrl spelling of the shortcut')
    assert.ok(html.includes('data-key="mac"'), 'no ⌘ spelling of the shortcut')
    // The script writes it as a `dataset` property; the stylesheet reads it as
    // an attribute. Assert both halves, or one can be renamed alone.
    assert.ok(html.includes('dataset.platform'), 'nothing stamps the platform before paint')
    const docs = await stylesheet('docs.css')
    assert.ok(
      docs.includes('[data-platform="mac"] kbd[data-key="mac"]'),
      'the stylesheet never reads the platform',
    )
  })

  test('carry one h1 and no skipped heading levels', async () => {
    for (const route of ['', 'docs', 'docs/guides/strings']) {
      const html = await page(route)
      const h1s = html.match(/<h1[\s>]/g) ?? []
      assert.equal(h1s.length, 1, `${route || '/'} has ${h1s.length} h1 elements`)
      assert.ok(!/<h[456][\s>]/.test(html), `${route || '/'} skips to h4+`)
    }
  })

  test('name every icon-only control', async () => {
    const html = await page('docs/guides/strings')

    // An icon-only button is announced as "button" and nothing else, so each
    // one needs a label. A button is icon-only when its content is markup with
    // no text of its own.
    const unnamed: string[] = []
    for (const match of html.matchAll(/<button\b([^>]*)>([\s\S]*?)<\/button>/g)) {
      const [, attributes = '', content = ''] = match
      const text = content.replace(/<[^>]+>/g, '').trim()
      if (text === '' && !attributes.includes('aria-label')) {
        unnamed.push(attributes.trim().slice(0, 80))
      }
    }

    assert.deepEqual(unnamed, [])
  })

  test('the skip link comes first in the document', async () => {
    const html = await page('docs')
    const skip = html.indexOf('Skip to content')
    const main = html.indexOf('id="doc-main"')
    assert.ok(skip > 0 && skip < main, 'the skip link must precede the content it skips to')
  })
})
