/**
 * Self-host the two webfonts.
 *
 * The design is built on Bricolage Grotesque and JetBrains Mono. Loading them
 * from Google would put a third-party request on the critical path of a site
 * whose entire argument is that it depends on nothing, and would hand every
 * reader's IP to another host. Downloading them once at build time costs a few
 * hundred kilobytes in the repo's build output and nothing at runtime.
 *
 * Only the `latin` subset is kept: the site is English throughout, and the
 * library's own rule is English-only prose. Latin-ext and Vietnamese would
 * double the payload to serve characters no page contains.
 *
 * Both families are variable fonts, so Google serves one identical file for
 * every weight -- verified by hash. Storing it once and declaring a weight range
 * saves 214 KiB over writing a file per weight.
 */

import { createHash } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { ROOT } from '../pipeline/corpus.ts'

const OUT = path.join(ROOT, 'public/fonts')

// Google serves a different CSS per user agent; this one gets woff2 with the
// full unicode-range split, which is what lets us keep only `latin`.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

interface Face {
  readonly family: string
  /** A range for a variable font, e.g. "400 700". */
  readonly weights: string
  readonly file: string
}

const FAMILIES: ReadonlyArray<{ query: string; family: string; slug: string }> = [
  {
    query: 'Bricolage+Grotesque:opsz,wght@12..96,400;12..96,500;12..96,700',
    family: 'Bricolage Grotesque',
    slug: 'bricolage-grotesque',
  },
  {
    query: 'JetBrains+Mono:wght@400;500;700',
    family: 'JetBrains Mono',
    slug: 'jetbrains-mono',
  },
]

/** Pull out only the `latin` blocks, which are the last of each unicode-range group. */
function latinFaces(css: string): Array<{ weight: string; url: string }> {
  const faces: Array<{ weight: string; url: string }> = []
  const blocks = css.split('@font-face')

  for (const [index, block] of blocks.entries()) {
    if (index === 0) continue
    const comment = blocks[index - 1]?.trimEnd().split('\n').at(-1) ?? ''
    if (!comment.includes('/* latin */')) continue

    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1]
    const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1]
    if (weight && url) faces.push({ weight, url })
  }

  return faces
}

async function main(): Promise<void> {
  await fs.mkdir(OUT, { recursive: true })
  const written: Face[] = []

  for (const { query, family, slug } of FAMILIES) {
    const css = await (
      await fetch(`https://fonts.googleapis.com/css2?family=${query}&display=swap`, {
        headers: { 'user-agent': UA },
      })
    ).text()

    const faces = latinFaces(css)
    if (faces.length === 0) throw new Error(`no latin faces found for ${family}`)

    // One file per distinct payload. A variable font answers every weight with
    // the same bytes, so a file per weight would ship the same 75 KiB three times.
    const seen = new Map<string, string>()
    for (const { weight, url } of faces) {
      const bytes = Buffer.from(await (await fetch(url)).arrayBuffer())
      const digest = createHash('sha256').update(bytes).digest('hex')

      const existing = seen.get(digest)
      if (existing) continue

      const file = `${slug}.woff2`
      await fs.writeFile(path.join(OUT, file), bytes)
      seen.set(digest, file)
      written.push({ family, weights: `${weight} ${faces.at(-1)?.weight ?? weight}`, file })
      console.log(
        `  ${file}  ${(bytes.length / 1024).toFixed(0)} KiB  (weights ${faces.map((f) => f.weight).join(', ')})`,
      )
    }
  }

  // The stylesheet is generated rather than hand-written, so a font that failed
  // to download is a missing @font-face rather than a 404 at runtime.
  const stylesheet = [
    '/* Generated by scripts/fetch-fonts.ts. Do not edit. */',
    '@layer base {',
    ...written.map((face) =>
      [
        '  @font-face {',
        `    font-family: "${face.family}";`,
        '    font-style: normal;',
        `    font-weight: ${face.weights};`,
        '    font-display: swap;',
        `    src: url("/fonts/${face.file}") format("woff2");`,
        // Latin only, matching what was downloaded.
        '    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,',
        '      U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,',
        '      U+2212, U+2215, U+FEFF, U+FFFD;',
        '  }',
      ].join('\n'),
    ),
    '}',
    '',
  ].join('\n')

  await fs.writeFile(path.join(ROOT, 'app/styles/fonts.css'), stylesheet)

  const digest = createHash('sha256').update(stylesheet).digest('hex').slice(0, 12)
  console.log(`\n  ${written.length} faces, stylesheet ${digest}\n`)
}

try {
  await main()
} catch (error) {
  console.error(`\n  ${error instanceof Error ? error.message : String(error)}\n`)
  process.exit(1)
}
